version: '3.8'

services:
  flask-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
    restart: always

  nginx-frontend:
    image: nginx:latest
    ports:
      - "8005:80"
    volumes:
      - ./static:/usr/share/nginx/html
    depends_on:
      - flask-backend
    restart: always