version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    container_name: backend_app
    volumes:
      - ./backend:/app
    env_file: .env-prod
    depends_on:
      - db
    restart: always
  
  db:
    image: postgis/postgis:15-3.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: XoGvI0vSeqxsQv6
      POSTGRES_DB: gymnasium
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_static
    environment:
      - API_BASE_URL=https://gymnasium.edigistay.com
    ports:
      - "8006:80"
    depends_on:
      - backend

volumes:
  postgres_data:
